### ISSUE TITLE
Force VLAN through VPN not working

### ISSUE THREAD

**Issue by traktuner** [peacey/split-vpn#10]
Hello,

I am currently using an UDM-Pro + USW-24 Pro (Gen 2) switch. The routing is done by the L3 switch.
Is it possible, that FORCED_SOURCE_INTERFACE will not work in this configuration?
I want to force VLAN 20 through the VPN, but I can not find the interface "br20" via ifconfig.
Only br0 and br4040 (VLAN for Inter-VLAN switching) are present.

Do you see any other way in doing this? It would be tedious to force every MAC in this VLAN.

Thank you!

**Comment by peacey** [comment]
Hi @traktuner,

I see the issue. I did not think of this configuration, but since the bridge interface doesn't exist on the UDM/P, that option won't work. I unfortunately don't have a Layer 3 switch to test this configuration further.

But does this VLAN have a unique subnet associated to it, or is it a VLAN-only network? You can force whole subnets through like `FORCED_SOURCE_IPV4="192.168.6.0/24" for example. Would that work?

**Comment by traktuner** [comment]
Hey @peacey !
Thank you! Tried it and it works as it should.
It's a good workaround - this VLAN configuration changes IP-wise from time to time, so I have to remember to change the VPN.conf too. But it's all I needed.
Thanks :)

**Comment by peacey** [comment]
Great! One thing - if you use IPv6, you should also force by the IPv6 subnet too using `FORCED_SOURCE_IPV6`. Alternatively, you can turn off IPv6 for that VLAN so you don't have to bother with forcing IPv6 traffic or changing IPv6 subnets. 

I'll also add a note in the readme for others in the future that forcing by interface/VLAN only works for VLANs created on the UDM/P directly and not with L3 switches. 

Have a nice day @traktuner! I'll close this issue for now.
