### ISSUE TITLE
Conflicts with Hotspot Guest Network setups

### ISSUE THREAD

**Issue by frznfngrs** [peacey/split-vpn#101]
Hello and thank you for your wonderful work.   I have tried implementing this however have discovered a strange issue where when VPN is activated, that forced clients are being required to authenticate on my Guest network hotspot.     I am not exactly sure what to provide to help here but VLAN 1 is the default network, and where the few forced VPN IPs also exist.  This subnet is 192.168.1.x/24       The guest vlan/hotspot network is VLAN 15, IP subnet 172.16.0.0/24.      The Guest portal is initially available at 192.168.1.1 and after guest authentication they are isolated to the 172.16.0.0/24 network.

**Comment by peacey** [comment]
Hi @frznfngrs,

What are you using as the MARK value in your vpn.conf?

**Comment by frznfngrs** [comment]
ROUTE_TABLE=101
### MARK=0x696af100
PREFIX="VPN_"
PREF=99
DEV=tun0

The default I believe?

**Comment by frznfngrs** [comment]
Thanks a ton @peacey .   Love what you are doing with this.

**Comment by peacey** [comment]
Okay, I figured out the problem @frznfngrs. On the Ubiquiti APs, Ubiquiti has iptables rules that matches any packet with (MARK & 0xc0000000 == 0x40000000  or == 0x80000000) and redirects it to the guest network. For the default MARK in this script, we see that (0x696af100 & 0xc0000000 == 0x40000000). So that's why they're being redirected. 

So the solution is to just use a MARK that doesn't render that comparison true, like 0x169. Can you set `MARK=0x169` in your vpn.conf and see if it's still happening?

Thanks for reporting this, I wouldn't have known otherwise since I don't use the guest portal feature myself.

**Comment by TheLazyGeekGuy** [comment]
Just worked ! Thank you !
