### ISSUE TITLE
Not working properly when I tried to use force the traffic designated  to ipsets when using OpenVPN

### ISSUE THREAD

**Issue by mrmiywj** [peacey/split-vpn#111]
Hi, thanks a lot for creating such a fantastic project. I am setting up a VLAN on my UDM, which will only force traffics designated to IPs in China through VPN, else remains the same.

Here's what I did:
1. I downloaded ip lists from: http://www.ipdeny.com/ipblocks/data/countries/cn.zone
2. Using script to add the ip lists above to ipset.
3. My vpn.conf looks like:
```
FORCED_SOURCE_INTERFACE="br4" # only vlan4 will apply 
FORCED_IPSETS="VPN_LIST:dst" # destinations in VPN_LIST
```

After this, I connected my ipad to VLAN4 and used whatismyipaddress.com to check. I found the ip is from the vpn provider, instead of my ip. I double checked the ip of whatismyipaddress.com, which is not in my ipset: 
```➜  ~ ping whatismyipaddress.com
PING whatismyipaddress.com (104.16.155.36): 56 data bytes
64 bytes from 104.16.155.36: icmp_seq=0 ttl=56 time=10.993 ms
64 bytes from 104.16.155.36: icmp_seq=1 ttl=56 time=14.687 ms

# ipset test VPN_LIST 104.16.155.36
104.16.155.36 is NOT in set VPN_LIST.
```

Anything I may missed?

Thanks a lot for your project btw!

**Comment by peacey** [comment]
Hi @mrmiywj,

I believe your configuration is correct but the ip list you linked does not have the IP or subnet 104.16.155.36 in the list. Can you verify that IP or subnet containing this IP is in the list through searching it?

Also, the ipset VPN_LIST is an ipset group containing two ipsets within it, VPN_LIST4 for IPv4 and VPN_LIST6 for IPv6. So when doing a `ipset test` you should use VPN_LIST4 for IPv4 addresses. For example, all these commands search the list:

```sh
ipset test VPN_LIST4 104.16.155.36
ipset list VPN_LIST4 | grep -E "^104\."
cat cn.zone | grep -E "^104\."
```

You can see all the commands don't find the IP (especially the last one searching the actual file you linked), so the list doesn't contain the IP. 

On the other hand, if you try some IP that is in the list like 1.0.1.0, all the above commands show the IP exists in the list.

**Comment by mrmiywj** [comment]
Hi @peacey 

Thanks a lot for your reply.

> I believe your configuration is correct but the ip list you linked does not have the IP or subnet 104.16.155.36 in the list.
yes I think it's expected. My IP list only contains IPs in China but 104.16.155.36 is not in China. It's whatismyipaddress.com IP. So my understanding is when I use whatismyipaddress.com, my traffic should not go through the VPN? But in fact it showed my VPN ip address. 

Thanks!

**Comment by peacey** [comment]
Oh sorry @mrmiywj, I misread what you wanted. I see  now you only want to force traffic destined to IPs in this ipset and nothing else.

The problem is you forced br4, so any traffic originating from br4 will be redirected to the VPN. The FORCED_IPSETS and FORCED_SOURCE_INTERFACE are independent of each other. So FORCED_IPSETS will apply that rule for all hosts, not just br4 traffic. 

You can accomplish what you want however by using CUSTOM_FORCED_RULES_IPV4 instead of FORCED_* variables. First set both FORCED_SOURCE_INTERFACE and FORCED_IPSETS to empty , then set CUSTOM_FORCED_RULES_IPV4 to the following in your vpn.conf:

```ini
CUSTOM_FORCED_RULES_IPV4="
      -m set --match-set VPN_LIST dst -i br4
  "
```

That will add a rule to only force br4 traffic that is destined to those IPs in that list. 

Please try that and see if it works for you.

**Comment by mrmiywj** [comment]
It works perfectly. Thanks!
