### ISSUE TITLE
what is the format of the text file to store username and password for openVPN? 

### ISSUE THREAD

**Issue by alstergee** [peacey/split-vpn#113]
tried:
username password

username"username" password"password" 

i need a working example of some sort.

also the script runs and then asks for an "auth password" before returning "auth error" when i attempt to start the services

also can i get a working example of the config file that say sends all devices to VPN? 

great work so far thanks!

**Comment by peacey** [comment]
Hi @alstergee,

The format for the username-password.txt file is the username on the first line and the password on the second line. So:

```
username_here
password_here
```

> also the script runs and then asks for an "auth password" before returning "auth error" when i attempt to start the services

It sounds like it's asking for an auth password because it wasn't set up right? Please try to set up the password file correctly and see if it works. 

> also can i get a working example of the config file that say sends all devices to VPN?

You just need to add each VLAN to FORCED_SOURCE_INTERFACE in vpn.conf. How many VLANs do you use and what are they? You also want to force the default network through as well?

Thanks!

**Comment by alstergee** [comment]
You beautiful genius it's working now! Thank you so much!

**Comment by peacey** [comment]
Glad you got it working! I'm closing this now as it's resolved but feel free to re-open if you have any more questions.
