### ISSUE TITLE
FORCED_SOURCE_INTERFACE="br6" not working for VLAN 6

### ISSUE THREAD

**Issue by beep-sheep** [peacey/split-vpn#121]
Hi peacey, Thank you so much for this project! 
When I check the VPN client with FORCED_SOURCE_IPV4="192.168.1.84" my connected computer goes through the VPN. So the installation succeeded. When I clear this setting and set FORCED_SOURCE_INTERFACE="br6", it does not force my computer through the VPN. My default network is on VLAN 6. As I want all devices to go through the VPN, I thought that would be the better option. Just not get it working though. Any help is appreciated!
Regards, Erik

**Comment by peacey** [comment]
Hi @beep-sheep,

It should definitely work with FORCED_SOURCE_INTERFACE, unless you're using a L3 switch and set the switch as the gateway for the network instead of the UDMP. Are you using the UDM as the gateway for this network?

Also, you can use FORCED_SOURCE_IPV4 to force a whole subnet instead of a single IP. Like: `FORCED_SOURCE_IPV4="192.168.1.0/24"` or whatever your subnet is for the network you want to force.

**Comment by beep-sheep** [comment]
Hi @peacey ,
Odd. My UDM-SE has a rj45 lan cable coming in from my provider into its WAN port. I had my computer connected to the UDM-SE directly via a lan cable. I retried it with a USW Flex Mini inbetween. It gave the same result. When I set FORCED_SOURCE_INTERFACE="" and FORCED_SOURCE_IPV4="192.168.1.1/255" I run into a fatal error. The last lines are:

Tue Aug  2 10:11:58 2022 /etc/split-vpn/vpn/updown.sh tun0 1500 1552 10.10.100.6 10.10.100.5 init
[Tue Aug  2 10:11:58 CEST 2022] split-vpn: tun0 up: Loading configuration from /mnt/data/split-vpn/openvpn/nl-ams-3/vpn.conf.
[Tue Aug  2 10:11:59 CEST 2022] split-vpn: Using IPv4 gateway from table 201: dev ppp0.
iptables v1.6.1: invalid mask `200' specified
Try `iptables -h' or 'iptables --help' for more information.
Tue Aug  2 10:11:59 2022 WARNING: Failed running command (--up/--down): external program exited with error status: 2
Tue Aug  2 10:11:59 2022 Exiting due to fatal error

No matter what I specify as ip range, if there is a "/" in that value split-vpn ends with above error 2. It works fine with individual ip addresses.

I attached the vpn.conf file I used as well as three screen shots from my UDM-SE configuration (as I suspect it might be something in there): 
[vpn.conf.txt](https://github.com/peacey/split-vpn/files/9240326/vpn.conf.txt)
<img width="849" alt="Screenshot 2022-08-02 at 10 21 20" src="https://user-images.githubusercontent.com/110387385/182328305-450c7120-97e7-469d-abe9-94dbbea99c21.png">
<img width="751" alt="Screenshot 2022-08-02 at 10 23 23" src="https://user-images.githubusercontent.com/110387385/182328312-858124ec-30c5-4c69-ab29-c479c9029cce.png">
<img width="880" alt="Screenshot 2022-08-02 at 10 24 45" src="https://user-images.githubusercontent.com/110387385/182328558-c3af91d8-6df5-4326-9611-1fde2889d2df.png">

**Comment by peacey** [comment]
What are you using to modify the vpn.conf file? It looks like there are weird characters in it due to a different encoding. If you're going to modify it with a text editor in windows or mac, make sure the line endings are set to Unix and that you don't save it as an RTF. It looks like due to these errors, the file is not being read correctly.

To avoid these issues, I suggest you modify it directly in the SSH terminal with vim. Copy over the original sample for a fresh start, then change the options you want with vim. Also use /24 not /255 (192.168.1.0/24), but honestly without the encoding problems the interface forcing should also work (br6).

**Comment by beep-sheep** [comment]
Hi @peacey,

I was just about to reply to you, as I have been digging into it today. 

Sorry I had bothered you. I'm giving myself a crash course into networking with this. I now understand the meaning of 192.168.1.1/24... where the last number refers to the required bits--not the range. CIDR. With that in mind and set, split-vpn is working! 

I used copy-paste to transfer the lines from my Mac Terminal to the Github webpage and the TextEditor on Mac. Display in the Terminal was via "cat vpn.conf".

The VLAN 6 I thought I had created in my network refers to a VLAN on the internet site (my ISP). As a router is the connection between the internal LAN and external WAN, that only specifies where to drop the outgoing packets. As I have no VLAN 6 on my internal network, my computer can't be in it, so the "br6" command won't route my computer through the VPN. I'm getting there... eventually. 

Very pleased with being able to use my VPN though. Thank you very much for your work, time and support!

Regards, Erik

**Comment by peacey** [comment]
Oh, I didn't see from your picture the VLAN was on the WAN. Nice catch. 

No worries, I'm glad you got it all figured out. There is definitely a learning curve! If you have anymore questions, feel free to ask, else you can close this issue.

Have a nice day!

**Comment by beep-sheep** [comment]
Enough network questions exist, but nothing split-vpn related. TY!!
