### ISSUE TITLE
Does this work on UDMP 2.4.23

### ISSUE THREAD

**Issue by aeglospt** [peacey/split-vpn#148]
As the subject says :-) anyone tried it yet?

**Comment by powellcn** [comment]
I did not do the update.  
Ubiquity has also pulled the update until a next minor version release.

However,
I don't see why this wouldn't work after the update as long as you are willing to re-install. 
You will need to take a look here https://github.com/unifi-utilities/unifios-utilities/issues/416 and reapply boost chicken's on boot script (using the UDM-SE method).

**Comment by peacey** [comment]
Hi @aeglospt,

Yes this works fine on UDM 2.x. The install script will install it to /data automatically. But you should use the systemd boot script instructions. You do not need any external boot utilities to run this at boot. Note that updating to 2.x will completely wipe your /mnt/data partition, so you will have to reinstall and reconfigure split-vpn. I would backup the split-vpn folder if you have a current config.

I have tested wireguard so far (and UDM 2.x has wg-quick and wireguard already installed, so no need to install any external utilities/modules for wireguard. 

One thing though, because we haven't had any updates yet on 2.x, I still need to test what happens to the split-vpn files when you update the system. If it's just like with UDM-SE with 2.x/3.x, then nothing will get wiped on /data and systemd, so hopefully should work fine. 

I will update the instructions shortly to reflect 2.x usage.

**Comment by peacey** [comment]
Closing this as completed as it does work on 2.4.x and README has been updated to reflect that.
