### ISSUE TITLE
Excempt Destination DNS

### ISSUE THREAD

**Issue by traktuner** [peacey/split-vpn#155]
Is there a way to excempt a destination by DNS name?
My usecase would be to add all domains used by e.g. GeForce Now or Xcloud to that list to make game streaming work. 
I have no idea which IP sets are used by those services and IPs there can change ...

Thank you for this great script, really looking forward using this when my UDMP gets upgraded to OS 2.x with supercharged WireGuard speeds 😉

**Comment by peacey** [comment]
Hello @traktuner,

Yes there is a way to force or exempt by domain name, as long as you use either the UDM's DNS server (dnsmasq) or a pihole installed on the UDM. Read the DNS forcing readme [here](https://github.com/peacey/split-vpn/tree/main/ipsets) to set it up. 

Basically how it works is we configure the DNS server so that everytime a specific domain is looked up, the DNS server adds the resolved IPs to an ipset. The ipset is then forced or exempted from the VPN in vpn.conf. This way the ipset will always contain the correct IPs, even when new IPs are resolved. 

If you're having trouble setting this up, just ask here.

**Comment by iaingeorge** [comment]
Is it possible when using DNSmasq in this fashion to forward all requests that don't match in the ipset file to an external piHole server? Effectively to forwarding any DNS requests that don't match the lookup table on the UDM to a secondary server on the network running piHole.

**Comment by peacey** [comment]
Hmm, I never thought of it like that but it is definitely possible when you think of it like that! Actually it's simpler than that. You just setup dnsmasq to forward ALL requests to your pihole (by default dnsmasq forwards all requests to your WAN's upstream servers). There's no need to split what get's forwarded, unless for some reason you need the internal dnsmasq to reply for some domains.

Here's how:

1. When following the ipsets guide, make sure to use the DNSMASQ options in VPN_domains.conf.
2. Add the following script to `/etc/split-vpn/ipsets/setup-forwards.sh`. Make sure to change 10.0.6.3 in the code below to your own PiHole's IP. 
    ```sh
    #!/bin/sh
    echo "add-dnsmasq-ipsets: Adding DNS forward"
    echo "server=/./10.0.6.3" > /run/dnsmasq.conf.d/z-forwards.conf
    echo "add-subnet=32,128" >> /run/dnsmasq.conf.d/z-forwards.conf
    killall dnsmasq
    ```
3. Make sure to run `/etc/split-vpn/ipsets/setup-forwards.sh` after you run `/etc/split-vpn/ipsets/add-dnsmasq-ipset.conf`. If you are using a run-vpn.sh script, add `/etc/split-vpn/ipsets/setup-forwards.sh` to it before you run the VPN.
4. In your LAN's DHCP settings, hand out the UDM's IP as the DNS. Do not give them the pihole IP directly. Or, you can also use DNS_IPV4_IP in vpn.conf to force VPN-forced clients to use dnsmasq.

Basically, we add a custom dnsmasq config that sets `server=/./10.0.6.3` so all requests are forwarded to the pihole (10.0.6.3 for me). We also add `add-subnet=32,128` so that origin IP is forwarded too (so pihole shows requests are coming from the correct client IP instead of UDM's IP).

Technically, you can also limit which domains are forwarded instead of forwarding all domains to pihole, but it's a bit more work. Also, you could do this the other way round by configuring your pihole to forward the exempted domains to dnsmasq, though it's also a bit more work. This seems to be the simplest solution, just adding two extra lines to the dnsmasq config and setting clients to use dnsmasq instead of pihole. 

You can try this method out and see if it works for you. Make sure to test your pihole is receiving the requests sent to dnsmasq, and that domain are exempted/forced based on your setup.

**Comment by peacey** [comment]
Okay, I've actually updated the ipsets scripts (in a separate branch) to add this forward as an option, so you don't have to do it manually as my previous reply. Instead follow these instructions:

1. Install the ipsets scripts from the new branch like so. Skip the installation step from the guide, of course.

    ```sh
    cd /etc/split-vpn
    curl -Lo split-vpn.zip https://github.com/peacey/split-vpn/archive/dnsmasq_forward.zip
    unzip -qo split-vpn.zip
    cp -rf split-vpn-dnsmasq_forward/ipsets ./ && rm -rf split-vpn-dnsmasq_forward split-vpn.zip
    chmod +x ipsets/*.sh
    ```

2. When following the ipsets guide, make sure to use the DNSMASQ options in VPN_domains.conf.
3. In your VPN_domains.conf, set FORWARD_SERVER to your external pihole (e.g.: `FORWARD_SERVER=10.0.6.3`). This option was newly added in the sample VPN_domains.conf.sample.
4. Follow the rest of the ipsets guide as usual to configure split-vpn with the ipsets.

See if that works for you and test if you run into any issues.

**Comment by iaingeorge** [comment]
I tried doing it manually, on the first run through. So far it has been stable, that said I did need to restart my UDM SE after setup as dnsmasq wasn’t responding to requests. I’ll try giving the less manual edition in the next few days here.

Is this solution limited to one forward server, or can I have two for redundancy?

**Comment by peacey** [comment]
Odd your dnsmasq wasn't responding before a restart. I tested this on my end and it worked fine without needing to restart the system. So you're saying after you restarted, you set up dnsmasq again and it ended working without needing to restart again? 

As for redundancy, it is possible to specify multiple servers by adding another server= line. However, Ubiquiti has configured the dnsmasq server with all-servers parameter enabled, which means all servers will be contacted and the fastest one will respond. So you won't have control over always going through the first then second only if first fails. It will always try both and give the first reply it got. Something like this is how we should configure it for multiple servers,

```ini
server=/./10.0.6.3
server=/./10.0.6.4
```

I haven't tested the multiple servers case though, so will have to do that to see if it works well. You can test it if you like too.

**Comment by peacey** [comment]
Sorry for the commit spam. Anyhow, I updated the dnsmasq_forward branch to support multiple forward servers (the variable name was also changed to FORWARD_SERVERS with an S). So you should be able to specify multiple servers now like this in your VPN_domains.conf after updating to that branch again:

```ini
FORWARD_SERVERS="10.0.6.3 10.0.6.2"
```

Also, I tested it on my end and it seems to work well with redundancy (dnsmasq contacts all servers then replies with the fastest reply). Note if none of your piholes/servers are responding, then dnsmasq won't be able to respond either.

**Comment by peacey** [comment]
Sorry for the spam, didn't realize it was hapenning everyime i did a force push on the branch. Anyhow, this FORWARD_SERVER feature has been merged in the main branch now so I'm closing this. Feel free to re-open if you have any more issues.

**Comment by bbruenings** [comment]
> Hmm, I never thought of it like that but it is definitely possible when you think of it like that! Actually it's simpler than that. You just setup dnsmasq to forward ALL requests to your pihole (by default dnsmasq forwards all requests to your WAN's upstream servers). There's no need to split what gets forwarded, unless for some reason you need the internal dnsmasq to reply for some domains.
> 
> 
> 
> Here's how:
> 
> 
> 
> 1. When following the ipsets guide, make sure to use the DNSMASQ options in VPN_domains.conf.
> 
> 2. Add the following script to `/etc/split-vpn/ipsets/setup-forwards.sh`. Make sure to change 10.0.6.3 in the code below to your own PiHole's IP. 
> 
>     ```sh
> 
>     #!/bin/sh
> 
>     echo "add-dnsmasq-ipsets: Adding DNS forward"
> 
>     echo "server=/./10.0.6.3" > /run/dnsmasq.conf.d/z-forwards.conf
> 
>     echo "add-subnet=32,128" >> /run/dnsmasq.conf.d/z-forwards.conf
> 
>     echo "no-resolv" >> /run/dnsmasq.conf.d/z-forwards.conf
> 
>     killall dnsmasq
> 
>     ```
> 
> 
> 
>     * Don't forget to run `chmod +x /etc/split-vpn/ipsets/setup-forwards.sh` to allow executable permissions on the script.
> 
>     
> 
> 3. Make sure to run `/etc/split-vpn/ipsets/setup-forwards.sh` after you run `/etc/split-vpn/ipsets/add-dnsmasq-ipset.conf`. If you are using a run-vpn.sh script, add `/etc/split-vpn/ipsets/setup-forwards.sh` to it before you run the VPN.
> 
> 4. In your LAN's DHCP settings, hand out the UDM's IP as the DNS. Do not give them the pihole IP directly. Or, you can also use DNS_IPV4_IP in vpn.conf to force VPN-forced clients to use dnsmasq.
> 
> 
> 
> Basically, we add a custom dnsmasq config that sets `server=/./10.0.6.3` so all requests are forwarded to the pihole (10.0.6.3 for me). We also add `add-subnet=32,128` so that origin IP is forwarded too (so pihole shows requests are coming from the correct client IP instead of UDM's IP), and `no-resolv` so dnsmasq doesn't contact any other dns servers (like WAN DNS) other than the forwarded one.
> 
> 
> 
> Technically, you can also limit which domains are forwarded instead of forwarding all domains to pihole, but it's a bit more work. Also, you could do this the other way round by configuring your pihole to forward the exempted domains to dnsmasq, though it's also a bit more work. This seems to be the simplest solution, just adding two extra lines to the dnsmasq config and setting clients to use dnsmasq instead of pihole. 
> 
> 
> 
> You can try this method out and see if it works for you. Make sure to test your pihole is receiving the requests sent to dnsmasq, and that domain are exempted/forced based on your setup. 

Hey together, thank you for the great work. I'm currently struggling on how to limit which Domains are forwarded to the dns server. Is there an option to limit the forward to dns servers just for specified Domains instead of all requests? 

Thank you in advance.

**Comment by iaingeorge** [comment]
Peacy, finally getting back to this. Given this is part of the main branch is there a suggested path for upgrading split-vpn to the latest version in the main branch? Do I need to remove it and reinstall?

From what I can see here there are some changes to the conf files that have been incorporated, so I imagine at the least these will need to be changed in my config even if the shell scripts were updated.
