### ISSUE TITLE
ExpressVPN on UDM Pro

### ISSUE THREAD

**Issue by sonnyh1** [peacey/split-vpn#21]
Hi,
I recently replaced my old router, etc. with UDM Pro, which is running
Network Version 6.2.25/Firmware Version 1.9.3

I was also running ExpressVPN on my old system.

I am administrating the UDM Pro via windows 10

My questions are:
1 - how can I run ExpressVPN on the UDM Pro?
2 - Being new to the UDM and not familiar with UDM Utilities Boot Script is there any detailed information on how to run the utility.
3 - How bullet proof is the installation process?

Thank you

**Comment by peacey** [comment]
ExpressVPN works fine with this script, just try to follow the tutorial in the README and tell me if you run into any trouble. The readme links to the boot script as well with a tutorial on how to set that up. 

ExpressVPN gives you a custom openvpn config, you would just need to download that config from the online portal for your chosen server, and copy it to the UDMP as explained in the tutorial.  Also make sure to get your VPN credentials from the portal. ExpressVPN explains how to download the configuration [here](https://www.expressvpn.com/support/vpn-setup/manual-config-for-linux-with-openvpn/).

The installation of the script is simple, and it works with the UDM Utilities on-boot-script (if set up) to make it start on boot. The boot script also survives firmware upgrades (most of the time, but no guarantees since a firmware upgrade can break the boot script if Ubiquiti does something unexpected and new). 

For running the script itself, it is hopefully bug free (but no guarantees), but it will error if you have any configuration problems. You can check the errors in the logs or output and fix your configuration. Also no guarantees it will work with every firmware upgrade, though I doubt there will ever be a problem. 

Just try out the README and tell me if you get stuck.

**Comment by sonnyh1** [comment]
Thank you for your reply.
I will read through your suggested materials and link.
Does the script live on the UDM/P?  For some reason I get the impression, incorrectly, that it lives externally on a Linux box.

⁣Best                                                (בס"ד)
Sonny
(Y5.76K Compliant)
--------------------------------------------------------
Sonny Hersh 
AHA: BLS / HeartSaver / CPR / AED - Instructor
ACS: Stop the Bleed - Instructor 
CERT ￼ Community Emergency Response Team
CSN Chicago, Community Safety Network - Director Communications/Technology
US Army MARS FEMA Region 5 Executive Officer
Proud, Professional, Ready
SHARES Member Station

Get BlueMail for Android ​

**Comment by peacey** [comment]
Yes the script lives on the UDM. The OpenVPN client is run directly on the UDM. The script does also have an option to use an external VPN client on another machine, but I don't think that's what you're looking to do.

**Comment by peacey** [comment]
Hi @sonnyh1,

I am closing this issue now but if you encounter any problems while setting up or need some help, just reopen it. Thanks!
