### ISSUE TITLE
dns multiple

### ISSUE THREAD

**Issue by theeddie** [peacey/split-vpn#25]
is there a way to set multiple dns servers

**Comment by peacey** [comment]
Hi @theeddie,

Unfortunately there isn't currently because the DNS forcing is done by a DNAT iptables rule, and the DNAT rule can only forward to one destination (usually, read on below). 

Technically, this is possible with the iptables statistics module, which allows us to create DNAT rules that rely on a probability of being chosen. The problem is the UDMP does not include the iptables statistics module by default. Which means we would have to compile the statistics module like the wireguard module, and we would have to recompile it for every new version (and hope they give us the new kernel when they update it). 

If you really want this option, I could compile the statistics module and see if it will work out and you can test it out too.

**Comment by theeddie** [comment]
Thanks
