### ISSUE TITLE
FORCED_SOURCE_MAC not working

### ISSUE THREAD

**Issue by traktuner** [peacey/split-vpn#38]
Hello,
I'd like to move from FORCED_SOURCE_IP to FORCED_SOURCE_MAC in vpn.conf.
FORCED_SOURCE_IP is working fine. I included the whole IP subnet in the config file (10.x.x.0/24)
But due to some changes in my network I have to user FORCED_SOURCE_MAC. When I add my iPhone's MAC address there, it's not working (private Wi-Fi address is of course turned off on my iPhone so the real MAC address is being used).
I have a L3 switch configuration where switching is done on my main switch and not on the UDM-Pro. But I guess that should not be an issue since the UDM-Pro also recognizes the MACs of the devices.
Do you have any recommendations what I could try?
Thank you!

**Comment by peacey** [comment]
Hi @traktuner,

Unfortunately a L3 switch rewrites the MAC to itself when forwarding the packet to the next upstream router

**Comment by traktuner** [comment]
He @peacey!
I see, thanks for the clarification! Including specific MACs would be just easier for me.
Then I would use my alternative choice and still add the subnet to FORCED_SOURCE_IP but use a list of exceptions in EXEMPT_SOURCE_IPV4 where I have to reserve some IP addresses.

Thank you!

**Comment by peacey** [comment]
If you just want to force a single IP and not the whole subnet, why can't you just add your phone's IP to FORCED_SOURCE_IP instead? You can even use the phone's MAC to create a DHCP reservation in the Unifi controller, so that the phone always gets the same IP.

The only time I wouldn't recommend FORCED_SOURCE_IP is if you are using IPv6, since IPv6 addresses are random and cannot be assigned like with IPv4 DHCP reservations. That's why I also prefer to force by MAC for single clients (or interface for a whole subnet) when possible.

**Comment by traktuner** [comment]
Hello,
I had Clients and Servers in different VLANs, now they are on a single "trusted" VLAN. However, servers need to be excluded from the VPN, and some other devices, but I still want all devices I connect to my internal WiFi to user the VPN. So for me the exclude-list is perfectly fine for me now - thank you :)
