### ISSUE TITLE
vpn-slice in openconnect?

### ISSUE THREAD

**Issue by joshuisken** [peacey/split-vpn#46]
Thanks for providing split-vpn!
Still I have a feature request.

I'm using [vpn-slice](https://github.com/dlenski/vpn-slice) to reduce traffic through my VPN provider.
Would be nice to have this capability on my udmp router instead of only a single machine.
I assume this involves modifying the Dockerfile for udm-openconnect and maybe using a different way than vpn.conf for configuration. Optionally I can try out myself based on your Dockerfile.
Maybe it is not compatible with other VPN clients?

On my linux box I'm using something like:
```
$ sudo openconnect \
     --background \
     --quiet \
     --authgroup=2 \
     --user=username \
     --script='...../bin/vpn-slice \
	 domain1.com \
	 domain2.com \
     	 x.x.0.0/16' \
     https://vpnprovider.com/
```
So that only domain[12] and x.x.0.0/16 are routed through the VPN.

I would like to move this functionality to the udmp and have one or two other machines using that same VPN connection.
Is something like that doable?

Thanks!

**Comment by peacey** [comment]
Hello @joshuisken,

The vpn-slice script is basically a split-tunnel script, similar to split-vpn. You can also force by domain or specific destination route using split-vpn, so you don't need to use both scripts together. You certainly can use them together with some effort, but it might make things more complicated because both split-vpn and vpn-splice handle adding routes and stuff and we would have to modify one or the other so they do not conflict.

If you give me more information, I can tell you how to set this up with split-vpn instead of vpn-slice. Here are my questions: 

1. Are domain1.com and domain2.com just normal domains that can be resolved using any DNS, or are they private domains that need to be resolved using the VPN's DNS?
2. Do you use the UDMP's built-in DNS server for UDMP-clients? The split-vpn's domain forcing works with the UDMP's DNS server so just checking. 
3. Do you want to force these domains/destinations to go through the VPN for every client on the UDMP, or only specific clients?

Regards,
Peacey

**Comment by joshuisken** [comment]
Hi Peacey,

I was actually also expecting it would work the same way, but maybe I did not grasp it completely yet.To answer your questions:

1. Domain1.com and domain2.com are indeed normal domains which can be resolved with any DNS.
2. Indeed I'm using the UDMP DNS server, though I'm considering using pihole or something more basic with dnsmasq since I used that before. Just for blocking adds.
3. The other domains are preferred to go through the VPN for all clients, though it is not necessary. It is important though for the clients in my network which I select to participate in the VPN connection.

Currently I'm only setting FORCED_SOURCE_IPV4 and FORCED_DESTINATIONS_IPV4, next to setting DNS_IPV6_IP="DHCP" for openconnect as advised.
It seems that all traffic from hosts in FORCED_SOURCE_IPV4 goes through the VPN, and I understand it is documented like that.
Would I would like, since the VPN is provided by my employer, that only few hosts can access servers of my employer. Most other traffic should go around VPN except for the few mentioned domains.

Hope this clarifies my wishes, and I hope I just misunderstood the docs ;-)

Thanks,
Jos

**Comment by peacey** [comment]
So the FORCED_SOURCE and FORCED_DESTINATIONS options work independently of each other. In other words, FORCED_DESTINATIONS forces these destinations for all UDMP clients, not just the ones specified in FORCED_SOURCE. 

So in your case you should just use FORCED_DESTINATIONS but set FORCED_SOURCE to empty. This way only the destination traffic is forced (regardless of source) and no source traffic is forced. 

Do domain1.com and domain2.com change their IP or do their IPs never really change? If the IP doesn't change, you can just add the domains to FORCED_DESTINATIONS as is (they will resolve when the rules are added). However, if the domain can return different IPs or the IP changes once a while, you should set up proper domain forcing by following [this guide](https://github.com/peacey/split-vpn/blob/main/ipsets/README.md). That works with both the built-in dnsmasq or pihole (if it's running on the UDMP not externally). 

For the simplest case where the IP doesn't change, your vpn.conf should have these options:

```
FORCED_SOURCE_IPV4=""
FORCED_DESTINATIONS_IPV4="x.x.0.0/16 domain1.com domain2.com"
DNS_IPV4_IP=""
```

I set DNS_IPV4_IP to empty so that your clients use the UDMP DNS server (which should be provided by DHCP). 

Please try the above suggestions and tell me if it works for you or if you need more granular control (forcing destinations from only certain clients instead of all).

**Comment by joshuisken** [comment]
My understanding was indeed correct, thanks.

I've tried with DNS_IPV4_IP empty and DHCP, in both cases access to domain[12].com work perfectly.
BTW, please note that I was using ip-ranges for domain[12] in vpn.conf anyway, I did not try to put the domain names there yet.

When I try to connect to a server within my employers network it does not find a route, in either case of the value DNS_IPV4_IP.
Also, in either case, nslookup the returns the same IP-address of a server. Nslookup always returns the UDMP IP-address as DNS server.
I'm only capable to connect to a server from a client if I add that client to FORCED_SOURCE. But that implies that all traffic will go through the VPN connection.

I also tried adding/removing the ip-range of my employer to FORCED_DESTINATIONS but that seems to make no difference.
You can assume that was x.x.0.0./16 in the example.

In fact what I try to achieve is that only few clients within my network (which I really trust) can access my employer's servers, which can access domain[12] over VPN with the rest of traffic directly to internet (to achieve good throughput).
Any other client can preferably access domain[12] via VPN.

I haven't looked in ipsets yet since it seems I do not need it at this point.

**Comment by peacey** [comment]
Hmm, it should work fine, just tried it on my end with only FORCED_DEST and no FORCED_SOURCE and it worked.

Let's try something very simple. Pick one server of your employer's on the VPN and let's try that. Let's say the server address is 10.2.3.4. in your VPN config:

1. Set FORCED_SOURCE_IPV4=""
2. Set FORCED_DESTINATIONS_IPV4="10.2.3.4"

Then restart the VPN and try to ping and access 10.2.3.4 from your UDMP-connected client.  

If it doesn't work, please show me the output of all of these commands (remove any public IPs if you see them):

```sh
iptables -t mangle -S
ip rule | grep fwmark
ip addr show dev tun0
ip route
ip route show table 101
```

Thanks!

**Comment by joshuisken** [comment]
If i set a specific IP-address x.x.y.z in FORCED_DEST it works. I was using x.x.0.0/16 and that does not seem to work.

Funny, since that x.x.0.0/16 style works for the other domains I want to route through the vpn. Somehow it fails for the IP addresses in my employers network. BTW, I do not know how everything (may be) subnetted in my employers network. Is that important when using /16?

When making a list of individual IP-addresses (x.x.a.b x.x.a.c) these hosts work fine. If I specify in FORCED_DEST something x.x.0.0/16  then all server connections x.x.y.z fail.

Also I realize between my WAN connection on the udmp and internet there is my providers IP4 modem/firewall, but I think that should have no influence.

Thanks!

**Comment by joshuisken** [comment]
Obviously leaving out x.x.0.0/16 from FORCED seems to me default.
If I have x.x.a.b and x.x.a.c in the list I can connect. If I want connect to x.x.a.d connection fails.
Adding x.x.0.0/16 makes all connections fail.

**Comment by peacey** [comment]
So I just tested a /16 subnet in FORCED_DEST and it worked fine on my end when I tested IPs on the subnet. Can you please double check there is no typo in your subnet? Do you have any conflicting subnets on the UDM that are the same/within the remote subnet?

Let's just make sure you have a fresh start. Please either restart the UDMP, or run this from your vpn.conf directory to delete previous rules:

```sh
podman rm -f openconnect-tun0
/mnt/data/split-vpn/vpn/updown.sh tun0 force-down
```

Then set the correct subnet in FORCED_DEST and start the VPN again. Try to ping an IP on that subnet from your UDMP-clients, and if it doesn't work, please show me the output of:

```sh
iptables -t mangle -S
ip route
```

Thanks.

**Comment by joshuisken** [comment]
Attached two logs of command sequences on UDMP, one with the passing config and one with the failing config.
I tested the connection to the first host in the list of FORCED_DEST

Failing:
`FORCED_DESTINATIONS_IPV4="XXX.YYY.35.28 XXX.YYY.34.56 XXX.YYY.0.0/16 XXX.YYY.34.93 XXX.YYY.11.234"`
Passing:
`FORCED_DESTINATIONS_IPV4="XXX.YYY.35.28 XXX.YYY.34.56 XXX.YYY.34.93 XXX.YYY.11.234"`
[fail.log](https://github.com/peacey/split-vpn/files/7270988/fail.log)
[pass.log](https://github.com/peacey/split-vpn/files/7270989/pass.log)

**Comment by peacey** [comment]
In your VPN route table, there is the VPN route: 

```sh
XXX.YYY.7.38 via 192.168.178.1 dev eth8 
```

I suppose XXX.YYY.7.38 is your VPN server IP correct? Is this XXX.YYY the same subnet as the XXX.YYY.0.0/16 you are trying to force? Or are these different X and Ys? If it's the same, that would explain it since adding a forced destination to this subnet will mean traffic to this IP goes out through the VPN (but this should be WAN traffic).

If it's the same subnet, can you add XXX.YYY.7.38 to EXEMPT_DESTINATIONS_IPV4 (so it goes out through the WAN) and add the /16 subnet in FORCED_DEST?

**Comment by joshuisken** [comment]
I made the log using a `sed' so any XXX.YYY is my employer's net.
XXX.YYY.7.38 is indeed the VPN server. 192.168.178.1 is my provider's modem WAN port. So a double firewall and I use 192.168.178.0/8 as a DMZ zone. The UDMP WAN port is 192.168.178.3

`EXEMPT_DESTINATIONS_IPV4="XXX.YYY.7.38"`
Adding above did not help, the same route is still in the table. 

It seems like that if following is in iptables all XXX.YYY.a.b connections fail:
`-A VPN_PREROUTING -d XXX.YYY.0.0/16 -j MARK --set-xmark 0x9/0xffffffff`

**Comment by peacey** [comment]
Ah, thank you so much for the information. I replicated the setup and I think I figured it out. I'm guessing the VPN is also giving you an IP on that same subnet, so we need to exempt your local VPN IPs assigned to the interface. Usually, the VPN public and private subnets don't overlap, so this was an unexpected situation. 

I've updated the script with the fix for this (you don't need to manually exempt the local IPs yourself). Can you please re-download the script, and re-run your VPN with the subnet in FORCED_DEST, and see if it works?

Thanks!

**Comment by joshuisken** [comment]
Success!  Indeed I'm aware that anyone connecting to the employers network receives an IP as well.
Actually, on servers you can see who is logged in from which IP and you can (I think...) see the hostname of the client.
Thanks so much solving the issue!

**Comment by peacey** [comment]
Happy it worked! 

Did you still want to restrict which UDMP clients get routed through the VPN for these subnets, or are you happy with the current setup where all UDMP clients go through the VPN for these subnets?

**Comment by joshuisken** [comment]
Ideally yes.

For now I have a single IP4 net, which I should partition. Having all kind of equipment, like cameras and other domotica stuff, but also mobiles for guests, in my network which should not be allowed to use the VPN. Ideally I need to put the clients which I use for work (and which I really can trust) in a subnet and only allow that subnet to use the VPN.
I didn't find time/motivation to do that yet. Having a USW and several smaller switches around the house. Also I don't know it is easily done on UDMP (with my current knowledge) and I'm not yet comfortable/confident enough with iptables, subnetting, and IPv6 (where I think I should go).
