### ISSUE TITLE
Configure NAT reflection

### ISSUE THREAD

**Issue by RomaDomor** [peacey/split-vpn#49]
Hi,

I have port forwarding setup for my OpenVPN server. Everything works fine.

But recently I faced problem of NAT reflection. I am unable to access websites that are pointed to my VPN server (and port forwarded) from server which hosts whose websites (and is in LAN that is under VPN).

Is there a way to make it work?

**Comment by peacey** [comment]
Hi @RomaDomor,

Sorry I'm a bit confused. Can you clarify which of the following you want to do? 

1. Access services through the VPN **public IP** through your normal WAN.
2. Access services through the VPN **public IP** through the VPN connection.
3. Access services through the VPN **private IP** through the VPN connection.

I'm assuming you want either 1 or 2 since you said NAT reflection. 

One question is are you port forwards on the VPN server side set up on your VPN's WAN interface or the private VPN interface? If they are set up on the VPN server's WAN, you will want to do scenario 1, but if they are set up on the VPN interface, then you want scenario 2. 

If you clarify, I can tell you what to do. Thanks!

**Comment by RomaDomor** [comment]
So the problem is that when from my home server I try to `wget` websites what are pointed to VDS server and then routed through OpenVPN to it (my home server), I get timeouts.
So here is the output of `wget mydomain`:
```
# wget mydomain
--2021-10-08 21:02:12--  http://mydomain/
Resolving mydomain (mydomain)... myvdsip, myvdsip6
Connecting to mydomain (mydomain)|myvdsip|:80...
```
And that's all, no matter how long I wait, that's all I get.

**Comment by RomaDomor** [comment]
It's not a good solution, I think.
But I tried It, now I can traceroute to VDS IP, but wget still timeouts. Strange...
