### ISSUE TITLE
Error: any valid prefix is expected rather than "vpn.endpoint.net:51822".

### ISSUE THREAD

**Issue by rjcds** [peacey/split-vpn#54]
Hi

I've got everything working (thank you !) to force a single IPv4 address on my network through a VPN.

However on startup I get the error

`Error: any valid prefix is expected rather than "vpn.endpoint.net:51822".`

The tunnel is up and all working, but not sure why it's logging this error ?

The client .conf file for this service is
```
[Interface]
PrivateKey = ***
Address = 10.11.4.50/16
PostUp = sh /etc/split-vpn/vpn/updown.sh %i up
PreDown = sh /etc/split-vpn/vpn/updown.sh %i down
Table = 101

[Peer]
PublicKey = ***
AllowedIPs = 0.0.0.0/1,128.0.0.0/1,::/1,8000::/1
Endpoint = vpn.endpoint.net:51822:51822
```

**Comment by peacey** [comment]
Hi @rjcds,

Thank you for reporting this. Actually it's because you can't use a hostname for VPN_ENDPOINT variables in vpn.conf. However, I just added a fix to get the endpoints directly from wireguard.

So can you update to the latest version (just run the installation script again), and set your VPN_ENDPOINT_* variables to empty in your vpn.conf so it gets it from wireguard instead. See if that makes the error go away.

Btw, in your post you wrote your Endpoint as"vpn.endpoint.net:51822:51822" with two ports. That's a typo, right? WireGuard would have thrown an error there.

**Comment by rjcds** [comment]
Thanks @peacey 

Yes that endpoint was a typo

I've updated, changed the vpn.conf VPN_ENDPOINT_* variables to empty as suggested, and the error has gone

Thanks for a great project !
