### ISSUE TITLE
delay systemctl service

### ISSUE THREAD

**Issue by hfagelnour** [peacey/split-vpn#56]
I am using a UDMPSE. the split-van is working fine when invoked manually.
I am now trying to start it upon boot but the systemctl service fail indicating the interface isn't available. I think this is because it tries to run and before the Site-to-site establish connection creating the interface.
is there any ways to delay the systemctl service run-van for like minute or so till the S2S starts and create its interface?

**Comment by peacey** [comment]
Hi @hfagelnour,

Instead of delaying the startup, you can set the service to restart on failure. Just modify `/etc/systemd/system/run-vpn.service` and add the following lines in the `[Service]` section after the `ExecStart` line. 

```
Restart=on-failure
RestartSec=5
```

This way it should keep restarting every 5 seconds if it fails until it works (supposedly when the interface comes up).

**Comment by hfagelnour** [comment]
Amazing @peacey 
worked like a charm. Can't thank you enough. I think this workaround should be added in the Wiki HOWTO in order for others benefit from it.
