### ISSUE TITLE
Help Wanted: Dedicated port to VPN?

### ISSUE THREAD

**Issue by Woebenskie** [peacey/split-vpn#58]
Huge thanks for the work on this project.

I'm a bit of a newbie if it comes to ip tables so I hope I can get some help this way.
I have setup the split vpn successful via wire-guard (mullvad). 
Now I have a client on a dedicated network port on my udm pro which is connected to a vlan, how do I "connect" this vlan/port to the vpn?

**Comment by peacey** [comment]
Hi @Woebenskie,

Do you want outbound communication from this port to be forced through the VPN tunnel? Not inbound/port forwarding, correct?

In that case, in your `vpn.conf` file, you can set either the `FORCED_SOURCE_IPV4_PORT` option to force a specific IP:port
or `FORCED_SOURCE_MAC_PORT` to force a specific MAC:port.

Does your server have a static IP or MAC Address associated to it? If you use IPv6, it's better to force by MAC:port since that will be constant. For example, setting this option will force any outbound communication from MAC Address 12:13:ab:ad:00:12 and port 333 to go through the VPN:

```
FORCED_SOURCE_MAC_PORT="both-12:13:ab:ad:00:12-333"
```

**Comment by Woebenskie** [comment]
hi,

thx for your quick response, 

I think I needed to be more clear, by network port I meant like a physical network interface (rj45) port.
But still thanks for you suggestion, what I actually needed was "FORCED_SOURCE_IPV4=" since the server has a static ip in a separate vlan (which is not required). And I wanted to route all traffic of that ip/vlan trough the vpn so i got it working that way. 

conclusion:  i just needed a better look a the vpn.conf file.
