### ISSUE TITLE
EXEMPT_DESTINATIONS_IPV4 not working on nexthop on VLAN

### ISSUE THREAD

**Issue by tracestep** [peacey/split-vpn#59]
I am new to UDM PRO (migrating from USG), and also a git noob, so sorry in advance if this issue breaks some etiquette rule...

I had `FORCED_SOURCE_IPV4="192.168.XXX.0/24"` to route a specific part of my /22 VLAN through a nexthop VPN gateway, and noticed that `EXEMPT_DESTINATIONS_IPV4=192.168.0.0/16` was not working - traffic destined to my other VLANs was being routed through the VPN, as if there was no exemption.

The exemption gets applied on the following piece of code in [add-vpn-iptables-rules.sh](https://github.com/peacey/split-vpn/blob/main/vpn/add-vpn-iptables-rules.sh):

```
for dest in ${EXEMPT_DESTINATIONS_IPV4}; do
    add_rule IPV4 mangle "PREROUTING ! -i ${dev} -d ${dest} -m mark --mark ${MARK} -j MARK --set-xmark 0x0"
done
```

The  `! -i ${dev}` bit was excluding packets from my VLAN interface from the exemption rule. Removing that part fixed the problem.

What's the purpose of excluding the DEV interface from the exemption matching? Is there a better way of excluding my other VLANs from the VPN or is this a bug in the code?

**Comment by peacey** [comment]
Hi @tracestep,

Thanks for reporting this and the fix. Initially, the `! -i ${dev}` portion was meant to ensure it doesn't select on incoming packets from the VPN interface. In this case, your VPN and forced devices are both on the same interface, which is causing the problem as you explained.

You're right that part is not needed. Since the command also only matches on marked packets, I think that takes care of incoming packets anyways. I have updated the script and removed the dev part. 

Please update the script on your end (just re-install it), and see if it works now. 

Thanks again for reporting this bug!

**Comment by tracestep** [comment]
Thanks for the quick response and fix. I can confirm that it works now. 

But, just before I forced-down the split-vpn script  prior to updating from github, I noticed that the strangest thing was happening: I could not mount nfsv4 shares from my client PC to a server, both on the same VLAN and same /22 subnet (the VLAN in which a specific portion goes through VPN)... the same was happening between a client and another server on the same VLAN, both outside of the FORCED_SOURCE_IPV4 segment. 

When I forced-down the split-vpn, I was able immediately mount the share. They were both connected to a non-unifi switch, which itself is connected to the UDMPRO; even if they were on the UDMPRO switch, packets within the same VLAN should not be routed in any way by the UDMPRO, right?

Here is the modified portion of my config (br16 is on 192.168.16.0/22):

```
FORCED_SOURCE_INTERFACE=""
FORCED_SOURCE_IPV4="192.168.18.0/24"
EXEMPT_DESTINATIONS_IPV4="192.168.0.0/16 10.0.0.0/8 172.16.0.0/12"
KILLSWITCH=1
REMOVE_KILLSWITCH_ON_EXIT=0
VPN_PROVIDER="nexthop"
VPN_ENDPOINT_IPV4="192.168.16.12"
GATEWAY_TABLE="disabled"
ROUTE_TABLE=18
MARK=0x8
PREFIX="VPNB_"
PREF=18
DEV=br16
```
I didn't alter any DNS rule (DNS is also on the same VLAN), and DNS to the server seemed to be resolving fine.

After applying your fix (which I saw also altered some nat rules), everything seems to be working ok. Can you think of anything related to routing / iptables that could be affecting NFS within a VLAN?

Anyway, feel free to close the issue, since the original problem is fixed :-)

**Comment by peacey** [comment]
Just to clarify, are you saying your NAS works fine now after the updated fix with the VPN turned on? 

Yes, same VLAN traffic does not go back to the router and is not NATed/mangled, so that's weird your NFS wasn't working. Did you try to connect by IP or hostname? 

I did add a masquerade fix as you saw that was masquerading (SNATing) all traffic instead of just the forced/marked traffic. This was only an issue when the DEV used is a LAN interface as is the case with nexthop. And this would have only affected inter-VLAN traffic, so it's odd your NFS wasn't working on the same VLAN.

**Comment by peacey** [comment]
Btw, I also noticed you're using the killswitch. Just be aware that the killswitch only makes sure that the packets are going out of the VPN interface (in your case, br16). In the case of nexthop, the killswitch will still let the traffic through even if the VPN is NOT enabled on the nexthop computer. 

So if you want to use the killswitch with nexthop, it is necessary to make sure that the nexthop computer has its own separate killswitch that ensures everything goes out the VPN only.

**Comment by tracestep** [comment]
Yes, it seems to be working now after your fix. It was not after my fix in which I just removed the `! -i ${dev}` piece in the code (albeit in a weird way, NFS worked if the connection to the server was already established, but I could not make a new connection - tested twice, immediate connection after force-down split-vpn). I was just wondering if you had any explanation for that weird behavior - my setup is by no means standard, anyway - maybe it has something to do with my NFS server being dual-homed on a management VLAN... closing the issue for now. :-)

Yes, I am aware about the killswitch, my nexthop won't route packets if the VPN is not connected (BTW, I am only using nexthop to get everything working again after I migrated from USG to UDMPRO, I plan to implement openvpn client directly on the UDMPRO with split-vpn next).
