### ISSUE TITLE
can't open './vpn.conf': No such file or directory

### ISSUE THREAD

**Issue by Archerious** [peacey/split-vpn#7]
```
# /mnt/data/openvpn/updown.sh tun0 force-down
Loading configuration from /mnt/data/on_boot.d/vpn.conf.
/mnt/data/openvpn/updown.sh: source: line 138: can't open './vpn.conf': No such file or directory

```
```
# /mnt/data/openvpn/updown.sh tun0 force-down
Loading configuration from /mnt/data/openvpn/vpn.conf.
/mnt/data/openvpn/add-vpn-iptables-rules.sh: source: line 234: can't open './vpn.conf': No such file or directory

```
Adjusted lines 138 and 234 from `./vpn.conf` to `/mnt/data/openvpn/nordvpn/vpn.conf`. Ran `#/mnt/data/openvpn/updown.sh tun0 force-down` and then started on boot script for vpn, and then all is working properly. Very odd but this seems to have only happened after I updated my UDM to 1.8.6.

**Comment by peacey** [comment]
Hi @Archerious,

You shouldn't need to adjust any lines. You will break multiple VPN configuration support like that. 

The problem was that you didn't `cd` into the NordVPN directory before running the force-down command. The script picks up the VPN.conf file from that directory you're in. So if you notice in the run script, we first `cd` into the correct directory before doing anything. 

Basically, you should run it this way:

``
