### ISSUE TITLE
I got it kind of working, fantastic project

### ISSUE THREAD

**Issue by lrdfrd** [peacey/split-vpn#80]
I have a UDMP and got this working manually, I'm having issues with the load at boot script and exempting with built in dnsmasq 
(I do have pihole at 192.168.1.2)
for example, I watch spectrum tv on my Xbox, I need to exempt destination spectrum.com/spectrum.net or their IPs?

and no matter what I change the boot script doesn't seem to persist. it's still there but the links are gone.

I am not an expert, just comfortable enough to break stuff..........

*Why can't / wont ubiquiti just support openvpn/wireguard out of the box?!?!

**Comment by peacey** [comment]
Hi @lrdfrd,

What issues are you having with the boot script? Did you check what the log says (either openvpn.log or wireguard.log, whichever you're using) after you boot, and whether there are any errors or whether it's even starting at all?

For exempting spectrum TV, I honestly think it's not that easy because (1) you have to figure out all the IPs or domains they use for streaming and their domains can be literally anything - not just spectrum.com, and (2) they might use shared CDNs and exempting them might exempt other providers unexpectedly. In my opinion, the most reliable solution would be to just turn the VPN off or use another SSID on a different VLAN when you want to watch Spectrum TV. 

If you really want to try exempting spectrum TV, then you definitely can try. Exempting IPs is simple with the `EXEMPT_DESTINATIONS_IPV4` option, but for exempting domains you have to do the [following extra setup](https://github.com/peacey/split-vpn/blob/main/ipsets/README.md) to set up the ipsets. But in order to do that, clients have to be set to use the built-in DNS server on the UDM (dnsmasq) or a pihole server that's running on the UDM (since pihole uses dnsmasq). You cannot use an external pihole for domain forcing, because dnsmasq needs to add to the ipsets on the UDM and it can only do that if it's running on the UDM.

Setting it up is easy, but figuring out all the CDNs, IP blocks, and domains they use is where it gets tricky.

**Comment by lrdfrd** [comment]
Actually, now the boot script is working, I missed a step. I don't usually have much time during the week but I'm really hoping to get this running :) I'm sure the same goes for the destinations issue, feel free to close this. 

and again, great project.
