### ISSUE TITLE
Query: Has anyone implemented this on a CloudKey Gen2?

### ISSUE THREAD

**Issue by kolakidd** [peacey/split-vpn#81]
Sorry, not really an issue, but I'm a bit of a newb to Unifi and just wanted to check before I got all gung-ho

**Comment by kolakidd** [comment]
Or, rather. USG!

**Comment by peacey** [comment]
Hi @kolakidd,

The CloudKey is not a router, so that wouldn't work. 

The USG is an entirely different platform (EdgeOS/Vyatta), so it's not supported with this script which is for the Unifi OS platform.

However, for the USG, you can already do policy-based routing to a VPN tunnel without this script ([here's one tutorial I found](https://blog.rylander.io/2018/01/07/setup-split-vpn-on-unifi-usg-using-pbr/)). You can even install [wireguard on it](https://github.com/WireGuard/wireguard-vyatta-ubnt/wiki/EdgeOS-and-Unifi-Gateway).

**Comment by kolakidd** [comment]
Thank you so much for taking the time to write that up and provide the example!
