### ISSUE TITLE
Trying to get forced domains to work

### ISSUE THREAD

**Issue by 13mralex** [peacey/split-vpn#85]
Hello, having some trouble getting this to work. I am likely missing something, just don't know what. I am using Openconnect, here's my config: I took out the comments to make it easier to read.
```
FORCED_SOURCE_INTERFACE="10.15.0.1/24"
#FORCED_SOURCE_IPV4=""
#FORCED_SOURCE_IPV6=""
#FORCED_SOURCE_MAC=""

EXEMPT_SOURCE_IPV4=""
EXEMPT_SOURCE_IPV6=""
EXEMPT_SOURCE_MAC=""

DNS_IPV4_IP="DHCP"
DNS_IPV4_PORT=53
DNS_IPV4_INTERFACE=""

DNS_IPV6_IP="REJECT"
DNS_IPV6_PORT=53
DNS_IPV6_INTERFACE=""

KILLSWITCH=0
REMOVE_KILLSWITCH_ON_EXIT=1

REMOVE_STARTUP_BLACKHOLES=1

VPN_PROVIDER="openconnect"

#VPN_ENDPOINT_IPV4=""
#VPN_ENDPOINT_IPV6=""

GATEWAY_TABLE="auto"

ROUTE_TABLE=101
MARK=0x9
PREFIX="VPN_"
PREF=99
DEV=tun0

FORCED_IPSETS="VPN_FORCED:dst"
EXEMPT_IPSETS="VPN_EXEMPT:dst"
```

Here are my openconnect logs:
```
POST https://xxx.xxx/
Connected to x.x.x.x:443
SSL negotiation with xxx.xxx
Connected to HTTPS on xxx.xxx with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA512)-(AES-256-GCM)
XML POST enabled
POST https://xxx.xxx/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as 10.195.0.115, using SSL, with DTLS in progress
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS1.2)-(ECDHE-RSA)-(AES-256-GCM).
[Fri Feb 25 14:13:41 EST 2022] split-vpn: tun0 up: Loading configuration from /etc/split-vpn/config/vpn.conf.
[Fri Feb 25 14:13:41 EST 2022] split-vpn: Using IPv4 gateway from table 201: via 10.5.3.254 dev eth8.
```

I am using the default vpn_domains.conf just as a test for now. Whenever I browse to one of the forced domains, it times out, but exempt and all others work okay. I think I attempted a forced client, but I don't think I did it right. The pages loaded by my IP address remained unchanged. Also, the last line in the Openconnect log shows an IP range that I have not configured/don't use. Is that normal? My main network is on 10.15.0.1/24. Any help would be much appreciated!

**Comment by peacey** [comment]
Hi @13mralex,

Before trying to force by domain, I recommend you try to force by IP/subnet/interface to test out if the connection is in fact working first before you do something more complicated. 

Can you set `FORCED_SOURCE_IPV4` to an IP or subnet you want to force, such as "10.15.0.1/24"? I see you set FORCED_SOURCE_INTERFACE to the subnet, but that's incorrect. FORCED_SOURCE_INTERFACE is for VLANs (like br0, br3, br9, etc), not subnets.

Once you do that and restart the script, can you do the following checks? 

1. Run `ping -I tun0 1.1.1.1` on the UDMP to ping through the tunnel directly. This should work unless there is a problem with the VPN.
2. If 1 works, then check a computer on the forced subnet and see what WAN IP you get at https://ifconfig.co for example.

**Comment by 13mralex** [comment]
I commented out the forced sources altogether, but I should still be able to ping from the UDMP right?
```
# ping -I tun0 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
^C
--- 1.1.1.1 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```

That didn't work. But it looks like tun0 has an address and everything, is something else missing?

```
# /sbin/ifconfig -a

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.195.20.194  P-t-P:10.195.20.194  Mask:255.255.255.255
          inet6 addr: fe80::1225:b325:61a:3670/64 Scope:Link
          inet6 addr: fde1:4aae:e356:b3d9::10/64 Scope:Global
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1390  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:76 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:0 (0.0 B)  TX bytes:4392 (4.2 KiB)
```

**Comment by peacey** [comment]
When you connect via AnyConnect, do you get a WAN IP on the VPN when you check https://ifconfig.co and can browse the Internet with the connection? And you're able to ping through the tunnel on your Mac? Like `ping -b utun8 1.1.1.1`

> This network I'm connecting to utilizes DUO two-factor authentication

That definitely might affect it... Are you able to connect using the openconnect client (instead of anyconnect) not using duo two-factor authentication on your computer? 

Is this a public VPN I can subscribe to and test or is it a private one (university, etc)?

>  There are a bunch of routes listed in the logfile and I wonder if it's not translating properly. 

Thanks, I got the routes. However, when you ping through the tunnel, the routes shouldn't matter. So I don't think it's the routes. We can double-check the gateway route you're getting is the same on the UDM side though. You can check what the gateway route is by running `ip route show table 101` on the UDM after connecting to the VPN.

**Comment by peacey** [comment]
Sorry for the late response @13mralex. 

Can you clarify whether you want to route ALL internet through this VPN, or only route university internal subnets? I ask because the default behaviour of split-vpn is to route ALL internet, so if the remote VPN doesn't allow routing all Internet, it will drop connections destined to outside the internal network. 

As for pinging the internal IP. You are saying pinging an internal IP works when done on the UDM through the tunnel, but not when done from a forced client?

**Comment by 13mralex** [comment]
Going to open a new issue since it is no longer related to the original issue.
